<a href="https://colab.research.google.com/github/feracor/curso_basico_pandas_numpy/blob/main/clase6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
list(range(0,10)) # Lista en Python

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [7]:
np.arange(0,10) #Crea un array con valores indexados desde 0 hasta la posicion 10

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(0,20,2) # Crea lista que desde un inicio, valor final, multiplos

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [12]:
np.zeros(3) # Crea un array con ceros

array([0., 0., 0.])

In [17]:
np.zeros((5,3)) # crea una matriz con ceros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [18]:
np.ones((5,3)) # crea una matriz con unos

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [20]:
np.linspace(0,10,10) # Crea un array desde valor inicial, valor final index, cantidad de valores deseados en el rango establecido

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [22]:
np.eye(4) #Crea matriz 4x4 con diagonal de unos

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [24]:
np.random.rand() #genera un valor aleatorio 

0.26602248461439637

In [25]:
np.random.rand(5) #genera un valor aleatorio en cinco index

array([0.18706858, 0.47060419, 0.02893989, 0.8375285 , 0.88150037])

In [27]:
np.random.rand(3,4) #genera un valor aleatorio en una matriz de 3 x 4

array([[0.58022265, 0.82204413, 0.35367036, 0.09706653],
       [0.03916735, 0.49828611, 0.76382898, 0.99509873],
       [0.44866084, 0.52979582, 0.07020189, 0.67273829]])

In [28]:
np.random.randint(1,15) # genera un valor entero aleatorio entre 1 y 15

7

In [30]:
np.random.randint(1,15, (8,5)) # genera un valor entero aleatorio entre 1 y 15 en una matriz de 8x5

array([[ 1,  9,  9,  9, 11],
       [10,  2,  5,  8, 12],
       [ 5,  7, 12,  8,  9],
       [12,  1, 11, 11, 11],
       [ 9,  2, 14, 12, 13],
       [ 6,  1, 13, 14,  5],
       [11,  1,  6, 13,  7],
       [11, 10, 11,  9, 14]])