<a href="https://colab.research.google.com/github/feracor/curso_basico_pandas_numpy/blob/main/clase3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import numpy as np

In [8]:
lista = [1,2,3,4,5,6,7,8,9] #crear lista
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [9]:
arr = np.array(lista) # crear arreglo con la lista

In [10]:
type(arr)

numpy.ndarray

In [11]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
matriz = [[1,2,3],[4,5,6],[7,8,9]] #Crear matriz
matriz = np.array(matriz)   # Convertir mastriz en array
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
#Indexing
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
arr[0] #Accede al al primer elemento del arreglo, '1'. Entre corteches se pone el index

1

In [15]:
arr[1] #Accede al al primer elemento del arreglo, '2'. Entre corteches se pone el index

2

In [16]:
arr[0] + arr[5]   #Suma el primer elemento del arreglo con el sexto

7

In [17]:
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
matriz[0] #Muestra primer fila

array([1, 2, 3])

In [21]:
matriz[0,2] #Muestra valor de fila 1, columna 3

3

In [22]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
arr[0:3] #Hace slide desde [Primer index : Ultimo index menos uno]

array([1, 2, 3])

In [24]:
arr[:5] #Slide desde cero hasta : 5 index - 1

array([1, 2, 3, 4, 5])

In [26]:
arr[2:] # Slice desde 2do index : hasta que termina la lista

array([3, 4, 5, 6, 7, 8, 9])

In [27]:
arr[:] #muestra todo el array :

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
arr[::3] # muestra todo el array y los cuenta en un multiplos del ultimo valor x   [::x]

array([1, 4, 7])

In [31]:
arr[-1] #cuenta desde el ultimo elemto jacia el primero

9

In [32]:
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
matriz [1:] #Imprime filas desde segunda fila

array([[4, 5, 6],
       [7, 8, 9]])

In [35]:
matriz[1:,0:2] # Fila dos en adelante (1:) , (IMPORTANTE PONER LA COMA) columnas desde primera hasta segunda (0:2) ESTAN REFERENCIADA POR INDEX

array([[4, 5],
       [7, 8]])

In [38]:
 matriz[1,1] # Imprime dato en segunda fila, segunda columna (IMPORTANTE PONER LA COMA)

5

In [42]:
matriz[-1,1:3] # Imprime ultima fila, segunda y terera columna (IMPORTANTE PONER LA COMA)

array([8, 9])