<a href="https://colab.research.google.com/github/feracor/curso_basico_pandas_numpy/blob/main/clase5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
"""
DIMENSIONES
dim = 0 Scalar
dim = 1 Vector
dim = 2 Matriz
dim = 3
dim = m Tensor

"""


'\nDIMENSIONES\ndim = 0 Scalar\ndim = 1 Vector\ndim = 2 Matriz\ndim = 3\ndim = m Tensor\n\n'

In [7]:
# Scalar
scalar = np.array(42)
print(scalar)
scalar.ndim

42


0

In [9]:
# Vector
vector = np.array([0,1,2,3])
print(vector)
vector.ndim

[0 1 2 3]


1

In [11]:
# Matriz
matriz = np.array([[1,2,3],[4,5,6]])
print(matriz)
matriz.ndim

[[1 2 3]
 [4 5 6]]


2

In [12]:
matriz = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(matriz)
matriz.ndim

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


2

In [20]:
# TENSOR
tensor = np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]],[[11,12,13],[14,15,16],[17,18,19],[110,111,112]]])
print(tensor)
tensor.ndim

[[[  1   2   3]
  [  4   5   6]
  [  7   8   9]
  [ 10  11  12]]

 [[ 11  12  13]
  [ 14  15  16]
  [ 17  18  19]
  [110 111 112]]]


3

In [19]:
# AGREGAR O ELIMINAR DIMENSIONES

In [24]:
vector = np.array([0,1,2,3], ndmin = 10)
print(vector)
vector.ndim

[[[[[[[[[[0 1 2 3]]]]]]]]]]


10

In [29]:
# EXPANDIR DIMENSIONES
expand = np.expand_dims(np.array([1,2,3]), axis = 0) # SE AGREGA UNA DIMENSION EN LAS FILAS, para Python 0 refiere a filas y 1 a columnas
print(expand)
expand.ndim

[[1 2 3]]


2

In [31]:
# COMPRIMIR MATRIZ
print(vector, vector.ndim)
vector_2 = np.squeeze(vector) # Comprime la matriz solo hasta las dimensiones que son utilizadas
print(vector_2, vector_2.ndim)

[[[[[[[[[[0 1 2 3]]]]]]]]]] 10
[0 1 2 3] 1
