<a href="https://colab.research.google.com/github/feracor/curso_basico_pandas_numpy/blob/main/clase3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [9]:
lista = [1,2,3,4,5,6,7,8,9] #crear lista
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [10]:
arr = np.array(lista) # crear arreglo con la lista

In [6]:
type(arr)

numpy.ndarray

In [8]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
matriz = [[1,2,3],[4,5,6],[7,8,9]] #Crear matriz
matriz = np.array(matriz)   # Convertir mastriz en array
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
#Indexing
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
arr[0] #Accede al al primer elemento del arreglo, '1'. Entre corteches se pone el index

1

In [23]:
arr[1] #Accede al al primer elemento del arreglo, '2'. Entre corteches se pone el index

2

In [25]:
arr[0] + arr[5]   #Suma el primer elemento del arreglo con el sexto

7